language: go
go:
  - 1.4
  - 1.5
  - 1.6
  # Don't test on tip until Go 1.7 is in feature freeze (Jul 01 2016)
  # - tip
install: make install_ci
script:
 - make test_ci
 - make cover_ci
 # Travis restores Godeps to the workspace, which we want to ignore from lint.
 - rm -rf Godeps/_workspace/src
 - make lint

